### PR TITLE
Add Wave Function Collapse demo

### PR DESCRIPTION
**Pull request by pusewicz**

### CODE REVIEW

**Review by kfischer-okarin — DISMISSED** [review]

**Review by DSchaedler — COMMENTED** [review]
I'm not sure this fits in with Libraries, Frameworks and Wrappers. It is more of a Demo than its own development tool.

**Comment by pusewicz** [comment]
@DSchaedler Fair point. It can be used, as importing the `model`, `cell` and `tile` allows anyone to use it. I'm happy to move it to a Demos section.

**Comment by pusewicz** [comment]
@DSchaedler @kfischer-okarin This is now moved to Samples

**Review by DSchaedler — APPROVED** [review]

**Review by oeloeloel — APPROVED** [review]
lgtm

**Pull request merged**
